---
version: '3.7'
services:
  zookeeper-1:
    image: zookeeper:3.7.0
    hostname: zookeeper-1
    container_name: zookeeper-1
    volumes:
            - ../kafka-pki/keystore/zookeeper-1.keystore.jks:/security/zookeeper-1.keystore.jks
            - ../kafka-pki/truststore/zookeeper-1.truststore.jks:/security/zookeeper-1.truststore.jks
    ports:
      - "12181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
      ZOO_CFG_EXTRA: "sslQuorum=true
                serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory

                ssl.quorum.hostnameVerification=false
                ssl.quorum.keyStore.location=/security/zookeeper-1.keystore.jks
                ssl.quorum.keyStore.password=password
                ssl.quorum.trustStore.location=/security/zookeeper-1.truststore.jks
                ssl.quorum.trustStore.password=password

                secureClientPort=2281
                ssl.hostnameVerification=false
                ssl.keyStore.location=/security/zookeeper-1.keystore.jks
                ssl.keyStore.password=password
                ssl.trustStore.location=/security/zookeeper-1.truststore.jks
                ssl.trustStore.password=password"

  zookeeper-2:
    image: zookeeper:3.7.0
    hostname: zookeeper-2
    container_name: zookeeper-2
    volumes:
            - ../kafka-pki/keystore/zookeeper-2.keystore.jks:/security/zookeeper-2.keystore.jks
            - ../kafka-pki/truststore/zookeeper-2.truststore.jks:/security/zookeeper-2.truststore.jks    
    ports:
      - "22181:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
      ZOO_CFG_EXTRA: "sslQuorum=true
                portUnification=false
                serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory

                ssl.quorum.hostnameVerification=false
                ssl.quorum.keyStore.location=/security/zookeeper-2.keystore.jks
                ssl.quorum.keyStore.password=password
                ssl.quorum.trustStore.location=/security/zookeeper-2.truststore.jks
                ssl.quorum.trustStore.password=password

                secureClientPort=2281
                ssl.hostnameVerification=false
                ssl.keyStore.location=/security/zookeeper-2.keystore.jks
                ssl.keyStore.password=password
                ssl.trustStore.location=/security/zookeeper-2.truststore.jks
                ssl.trustStore.password=password"

  zookeeper-3:
    image: zookeeper:3.7.0
    hostname: zookeeper-3
    container_name: zookeeper-3
    volumes:
            - ../kafka-pki/keystore/zookeeper-3.keystore.jks:/security/zookeeper-3.keystore.jks
            - ../kafka-pki/truststore/zookeeper-3.truststore.jks:/security/zookeeper-3.truststore.jks
    ports:
      - "32181:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
      ZOO_CFG_EXTRA: "sslQuorum=true
                portUnification=false
                serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory

                ssl.quorum.hostnameVerification=false
                ssl.quorum.keyStore.location=/security/zookeeper-3.keystore.jks
                ssl.quorum.keyStore.password=password
                ssl.quorum.trustStore.location=/security/zookeeper-3.truststore.jks
                ssl.quorum.trustStore.password=password

                secureClientPort=2281
                ssl.hostnameVerification=false
                ssl.keyStore.location=/security/zookeeper-3.keystore.jks
                ssl.keyStore.password=password
                ssl.trustStore.location=/security/zookeeper-3.truststore.jks
                ssl.trustStore.password=password"

  broker-1:
    image: confluentinc/cp-kafka:7.0.1
    hostname: broker-1
    container_name: broker-1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "9191:9191"
      - "9291:9291"
    volumes:
        - ../kafka-pki/keystore/broker-1.keystore.jks:/etc/kafka/secrets/broker-1.keystore.jks
        - ../kafka-pki/truststore/broker-1.truststore.jks:/etc/kafka/secrets/broker-1.truststore.jks
        - ../kafka-pki/password.txt:/etc/kafka/secrets/password.txt
        - ./jaas/sasl-scram/ssl-scram-jaas-broker.conf:/etc/kafka/secrets/ssl-scram-jaas-broker.conf
 
    environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2281,zookeeper-2:2281,zookeeper-3:2281
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_SSL:SASL_SSL,SSL:SSL
          KAFKA_ADVERTISED_LISTENERS: SASL_SSL://broker-1:9191,SSL://broker-1:9291
          KAFKA_LISTENERS: SASL_SSL://broker-1:9191,SSL://broker-1:9291
          KAFKA_DEFAULT_REPLICATION_FACTOR: 3
          KAFKA_MIN_INSYNC_REPLICAS: 2
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
          KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/broker-1.keystore.jks
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: password
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/broker-1.truststore.jks
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: password

          KAFKA_SSL_CLIENT_AUTH: required
          KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/broker-1.keystore.jks
          KAFKA_SSL_KEYSTORE_PASSWORD: password
          KAFKA_SSL_KEY_PASSWORD: password
          KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/broker-1.truststore.jks
          KAFKA_SSL_TRUSTSTORE_PASSWORD: password

          KAFKA_SSL_KEYSTORE_FILENAME: broker-1.keystore.jks
          KAFKA_SSL_KEYSTORE_CREDENTIALS: password.txt
          KAFKA_SSL_KEY_CREDENTIALS: password.txt
          KAFKA_SSL_TRUSTSTORE_FILENAME: broker-1.truststore.jks
          KAFKA_SSL_TRUSTSTORE_CREDENTIALS: password.txt

          KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
          KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512

          KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer

          KAFKA_SUPER_USERS: "User:CN=broker-1,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA;
                              User:CN=broker-2,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA;
                              User:CN=broker-3,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA;
                              User:CN=admin,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA"          

          KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/ssl-scram-jaas-broker.conf"

  broker-2:
    image: confluentinc/cp-kafka:7.0.1
    hostname: broker-2
    container_name: broker-2
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "9192:9192"
      - "9292:9292"
    volumes:
        - ../kafka-pki/keystore/broker-2.keystore.jks:/etc/kafka/secrets/broker-2.keystore.jks
        - ../kafka-pki/truststore/broker-2.truststore.jks:/etc/kafka/secrets/broker-2.truststore.jks
        - ../kafka-pki/password.txt:/etc/kafka/secrets/password.txt
        - ./jaas/sasl-scram/ssl-scram-jaas-broker.conf:/etc/kafka/secrets/ssl-scram-jaas-broker.conf
 
    environment:
          KAFKA_BROKER_ID: 2
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2281,zookeeper-2:2281,zookeeper-3:2281
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_SSL:SASL_SSL,SSL:SSL
          KAFKA_ADVERTISED_LISTENERS: SASL_SSL://broker-2:9192,SSL://broker-2:9292
          KAFKA_LISTENERS: SASL_SSL://broker-2:9192,SSL://broker-2:9292
          KAFKA_DEFAULT_REPLICATION_FACTOR: 3
          KAFKA_MIN_INSYNC_REPLICAS: 2
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
          KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/broker-2.keystore.jks
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: password
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/broker-2.truststore.jks
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: password
          

          KAFKA_SSL_CLIENT_AUTH: required
          KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/broker-2.keystore.jks
          KAFKA_SSL_KEYSTORE_PASSWORD: password
          KAFKA_SSL_KEY_PASSWORD: password
          KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/broker-2.truststore.jks
          KAFKA_SSL_TRUSTSTORE_PASSWORD: password

          KAFKA_SSL_KEYSTORE_FILENAME: broker-2.keystore.jks
          KAFKA_SSL_KEYSTORE_CREDENTIALS: password.txt
          KAFKA_SSL_KEY_CREDENTIALS: password.txt
          KAFKA_SSL_TRUSTSTORE_FILENAME: broker-2.truststore.jks
          KAFKA_SSL_TRUSTSTORE_CREDENTIALS: password.txt

          KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
          KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512

          KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer

          KAFKA_SUPER_USERS: "User:CN=broker-1,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA;
                              User:CN=broker-2,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA;
                              User:CN=broker-3,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA;
                              User:CN=admin,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA"
          KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/ssl-scram-jaas-broker.conf"

  broker-3:
    image: confluentinc/cp-kafka:7.0.1
    hostname: broker-3
    container_name: broker-3
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "9193:9193"
      - "9293:9293"
    volumes:
      - ../kafka-pki/keystore/broker-3.keystore.jks:/etc/kafka/secrets/broker-3.keystore.jks
      - ../kafka-pki/truststore/broker-3.truststore.jks:/etc/kafka/secrets/broker-3.truststore.jks
      - ../kafka-pki/password.txt:/etc/kafka/secrets/password.txt
      - ./jaas/sasl-scram/ssl-scram-jaas-broker.conf:/etc/kafka/secrets/ssl-scram-jaas-broker.conf
 
    environment:
          KAFKA_BROKER_ID: 3
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2281,zookeeper-2:2281,zookeeper-3:2281
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_SSL:SASL_SSL,SSL:SSL
          KAFKA_ADVERTISED_LISTENERS: SASL_SSL://broker-3:9193,SSL://broker-3:9293
          KAFKA_LISTENERS: SASL_SSL://broker-3:9193,SSL://broker-3:9293
          KAFKA_DEFAULT_REPLICATION_FACTOR: 3
          KAFKA_MIN_INSYNC_REPLICAS: 2
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
          KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/broker-3.keystore.jks
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: password
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/broker-3.truststore.jks
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: password

          KAFKA_SSL_CLIENT_AUTH: required
          KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/broker-3.keystore.jks
          KAFKA_SSL_KEYSTORE_PASSWORD: password
          KAFKA_SSL_KEY_PASSWORD: password
          KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/broker-3.truststore.jks
          KAFKA_SSL_TRUSTSTORE_PASSWORD: password

          KAFKA_SSL_KEYSTORE_FILENAME: broker-3.keystore.jks
          KAFKA_SSL_KEYSTORE_CREDENTIALS: password.txt
          KAFKA_SSL_KEY_CREDENTIALS: password.txt
          KAFKA_SSL_TRUSTSTORE_FILENAME: broker-3.truststore.jks
          KAFKA_SSL_TRUSTSTORE_CREDENTIALS: password.txt

          KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
          KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512

          KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_SUPER_USERS: "User:CN=broker-1,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA;
                              User:CN=broker-2,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA;
                              User:CN=broker-3,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA;
                              User:CN=admin,OU=IT,O=Digital Infornation Inc CA Root Authority,L=Montreal,ST=QC,C=CA"

          KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/ssl-scram-jaas-broker.conf"






  







  

